# https://taskfile.dev

version: '3'

vars:
  BIN_NAME: sproxy
  DIST_DIR: dist
  # 默认平台
  DEFAULT_GOOS: linux
  DEFAULT_GOARCH: amd64
  DOCKERHUB_REPO: daiyuang/sproxy
  GHCR_REPO: ghcr.io/daiyuang/sproxy
  CONTAINER_PLATFORM: --platform linux/amd64,linux/arm64

tasks:
  clean:
    cmds:
      - rm -rf {{.DIST_DIR}}

  build:
    desc: 构建当前平台（默认启用 CGO）
    cmds:
      - go build -o {{.DIST_DIR}}/{{.BIN_NAME}} .

  build:all:
    desc: 构建所有平台（含 CGO）
    deps: [ build:linux, build:darwin, build:windows ]

  build:linux:
    desc: 构建 Linux 版本（带 CGO）
    deps: [ clean ]
    env:
      GOOS: linux
      GOARCH: amd64
    cmds:
      - mkdir -p {{.DIST_DIR}}/linux
      - go build -trimpath -ldflags="-s -w" -o {{.DIST_DIR}}/linux/{{.BIN_NAME}} .

  build:darwin:
    desc: 构建 macOS 版本（带 CGO）
    env:
      GOOS: darwin
      GOARCH: amd64
    cmds:
      - mkdir -p {{.DIST_DIR}}/darwin
      - go build -trimpath -ldflags="-s -w" -o {{.DIST_DIR}}/darwin/{{.BIN_NAME}} .
    deps: [ clean ]


  build:windows:
    desc: 构建 Windows 版本（带 CGO）
    deps: [ clean ]
    env:
      GOOS: windows
      GOARCH: amd64
    cmds:
      - mkdir -p {{.DIST_DIR}}/windows
      - go build -trimpath -ldflags="-s -w" -o {{.DIST_DIR}}/windows/{{.BIN_NAME}}.exe .

  build:docker:distroless:
    desc: 构建 Docker 镜像
    cmds:
      - docker buildx build {{.CONTAINER_PLATFORM}} --target distroless -t {{.BIN_NAME}}:latest -t {{.BIN_NAME}}:distroless .

  build:docker:alpine:
    desc: 构建 Docker 镜像
    cmds:
      - docker buildx build {{.CONTAINER_PLATFORM}} --target alpine -t {{.BIN_NAME}}:alpine .

  build:docker:debian:
    desc: 构建 Docker 镜像
    cmds:
      - docker buildx build {{.CONTAINER_PLATFORM}} --target debian -t {{.BIN_NAME}}:debian .

  build:docker:scratch:
    desc: 构建 Docker 镜像
    cmds:
      - docker buildx build {{.CONTAINER_PLATFORM}} --target scratch -t {{.BIN_NAME}}:scratch .

  build:docker:
    desc: build container
    deps: [ build:docker:scratch,build:docker:distroless,build:docker:alpine,build:docker:debian ]


  retag:
    desc: retag
    cmds:
      - docker tag {{.BIN_NAME}}:distroless {{.DOCKERHUB_REPO}}:distroless
      - docker tag {{.BIN_NAME}}:distroless {{.GHCR_REPO}}:distroless
      - docker tag {{.BIN_NAME}}:alpine {{.DOCKERHUB_REPO}}:alpine
      - docker tag {{.BIN_NAME}}:alpine {{.GHCR_REPO}}:alpine
      - docker tag {{.BIN_NAME}}:debian {{.DOCKERHUB_REPO}}:debian
      - docker tag {{.BIN_NAME}}:debian {{.GHCR_REPO}}:debian
      - docker tag {{.BIN_NAME}}:scratch {{.DOCKERHUB_REPO}}:scratch
      - docker tag {{.BIN_NAME}}:scratch {{.GHCR_REPO}}:scratch

  push:
    desc: push container
    cmds:
      - docker push {{.DOCKERHUB_REPO}}:distroless
      - docker push {{.GHCR_REPO}}:distroless
      - docker push {{.DOCKERHUB_REPO}}:alpine
      - docker push {{.GHCR_REPO}}:alpine
      - docker push {{.DOCKERHUB_REPO}}:debian
      - docker push {{.GHCR_REPO}}:debian
      - docker push {{.DOCKERHUB_REPO}}:scratch
      - docker push {{.GHCR_REPO}}:scratch

  check:
    cmds:
      - go tool staticcheck ./...